---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          href: https://old.reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/

- UWM:
    - Neurons:
        - abbr: NR
          href: https://uwm-amc.ivanticloud.com/
